# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  package:
    docker:
      - image: maven:3.6.3-jdk-11
    steps:
      - checkout
      - run:
          name: package code
          command: mvn clean package
  
  test:
    docker:
      - image: maven:3.6.3-jdk-11
    steps:
      - checkout
      - run:
          name: package code
          command: mvn test

  build-iamge:
    docker:
      - image: docker:17.05.0-ce-git  
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Build application Docker image
          command: |
            docker build  -t thongnq2/dev-ops-project-5:${CIRCLE_WORKFLOW_ID:0:7} .
      - deploy:
          name: Push application Docker image
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD            
            docker push "thongnq2/dev-ops-project-5:${CIRCLE_WORKFLOW_ID:0:7}"
workflows:
  say-hello-workflow:
    jobs:
      - package
      - test:
          requires: [package]
      - build-iamge:
          requires: [test]
        

